import {
  RADIO_ALERT_CONSTANTS,
  RADIO_TRIGGER_PRESETS,
  type RadioTriggerPreset,
} from '../../constants/f1';
import type { EngineerAlertSwitch } from '../../types/settings';

/**
 * Category master switches and per-alert switches shown in the radio settings panel. The server
 * turns them into the engine's enabled categories (engineer.EnabledCategoriesFromSwitches).
 */
export const ALERT_TOGGLE_KEYS = [
  'tyreAlertsEnabled',
  'damageAlertsEnabled',
  'ersAlertsEnabled',
  'brakesAlertsEnabled',
  'fuelAlertsEnabled',
  'rivalAlertsEnabled',
  'pitAlertsEnabled',
  'coachingAlertsEnabled',
  'teammateAlertsEnabled',
  'qualyAlertsEnabled',
  'flagsPensAlertsEnabled',
  'subTyreWear',
  'subTyrePuncture',
  'subTyreThermal',
  'subTyreCold',
  'subTyreCondition',
  'subTyreCrossover',
  'subDamageWing',
  'subDamageFloor',
  'subDamageEngine',
  'subDamageFaults',
  'subEngineTemp',
  'subErsLow',
  'subErsClipping',
  'subAeroZones',
  'subBrakeTemp',
  'subBrakeCold',
  'subBrakeBias',
  'subFuelDelta',
  'subFuelMix',
  'subUndercut',
  'subRivalDefend',
  'subRivalAttack',
  'subPitWindow',
  'subPitWindowClose',
  'subPitCleanAir',
  'subTyreSet',
  'subPitLane',
  'subPitEntryReminder',
  'subSectorDelta',
  'subStartProcedure',
  'subInlapCooldown',
  'subTeammateAhead',
  'subTeammatePit',
  'subQualyTraffic',
  'subQualyInvalid',
  'subQualyTime',
  'subQualyElim',
  'subSafetyCar',
  'subRedFlag',
  'subRain',
  'subTrackLimits',
  'subPenalties',
  'subFlags',
  'subRaceEvents',
] as const satisfies readonly EngineerAlertSwitch[];

export type AlertToggleKey = (typeof ALERT_TOGGLE_KEYS)[number];

// tsc fails here when the server knows a switch the panel doesn't show.
type NoMissingSwitches<T extends never> = T;
export type AllAlertSwitchesShown = NoMissingSwitches<Exclude<EngineerAlertSwitch, AlertToggleKey>>;
export type AlertToggles = Record<AlertToggleKey, boolean>;

export interface TriggerPresetValues extends AlertToggles {
  chatterCooldownSeconds: number;
}

type NamedTriggerPreset = Exclude<RadioTriggerPreset, typeof RADIO_TRIGGER_PRESETS.CUSTOM>;

export const TRIGGER_PRESET_VALUES: Record<NamedTriggerPreset, TriggerPresetValues> = {
  [RADIO_TRIGGER_PRESETS.IMMERSIVE]: {
    tyreAlertsEnabled: true,
    damageAlertsEnabled: true,
    ersAlertsEnabled: true,
    brakesAlertsEnabled: true,
    fuelAlertsEnabled: true,
    rivalAlertsEnabled: true,
    pitAlertsEnabled: true,
    coachingAlertsEnabled: true,
    teammateAlertsEnabled: true,
    qualyAlertsEnabled: true,
    flagsPensAlertsEnabled: true,
    chatterCooldownSeconds: RADIO_ALERT_CONSTANTS.CHATTER_PRESETS.NORMAL,
    subTyreWear: true,
    subTyrePuncture: true,
    subTyreThermal: false,
    subTyreCold: false,
    subTyreCondition: false,
    subTyreCrossover: true,
    subDamageWing: true,
    subDamageFloor: false,
    subDamageEngine: false,
    subDamageFaults: true,
    subEngineTemp: false,
    subErsLow: false,
    subErsClipping: false,
    subAeroZones: false,
    subBrakeTemp: false,
    subBrakeCold: false,
    subBrakeBias: false,
    subFuelDelta: false,
    subFuelMix: true,
    subUndercut: true,
    subRivalDefend: false,
    subRivalAttack: false,
    subPitWindow: false,
    subPitWindowClose: false,
    subPitCleanAir: false,
    subTyreSet: false,
    subPitLane: true,
    subPitEntryReminder: true,
    subSectorDelta: false,
    subStartProcedure: true,
    subInlapCooldown: false,
    subTeammateAhead: true,
    subTeammatePit: true,
    subQualyTraffic: false,
    subQualyInvalid: true,
    subQualyTime: false,
    subQualyElim: false,
    subSafetyCar: true,
    subRedFlag: true,
    subRain: true,
    subTrackLimits: false,
    subPenalties: true,
    subFlags: true,
    subRaceEvents: true,
  },
  [RADIO_TRIGGER_PRESETS.COACHING]: {
    tyreAlertsEnabled: true,
    damageAlertsEnabled: true,
    ersAlertsEnabled: true,
    brakesAlertsEnabled: true,
    fuelAlertsEnabled: true,
    rivalAlertsEnabled: true,
    pitAlertsEnabled: true,
    coachingAlertsEnabled: true,
    teammateAlertsEnabled: true,
    qualyAlertsEnabled: true,
    flagsPensAlertsEnabled: true,
    chatterCooldownSeconds: RADIO_ALERT_CONSTANTS.CHATTER_PRESETS.TALKATIVE,
    subTyreWear: true,
    subTyrePuncture: true,
    subTyreThermal: true,
    subTyreCold: true,
    subTyreCondition: true,
    subTyreCrossover: true,
    subDamageWing: true,
    subDamageFloor: true,
    subDamageEngine: true,
    subDamageFaults: true,
    subEngineTemp: true,
    subErsLow: true,
    subErsClipping: true,
    subAeroZones: true,
    subBrakeTemp: true,
    subBrakeCold: true,
    subBrakeBias: true,
    subFuelDelta: true,
    subFuelMix: true,
    subUndercut: true,
    subRivalDefend: true,
    subRivalAttack: true,
    subPitWindow: true,
    subPitWindowClose: true,
    subPitCleanAir: true,
    subTyreSet: true,
    subPitLane: true,
    subPitEntryReminder: true,
    subSectorDelta: true,
    subStartProcedure: true,
    subInlapCooldown: true,
    subTeammateAhead: true,
    subTeammatePit: true,
    subQualyTraffic: true,
    subQualyInvalid: true,
    subQualyTime: true,
    subQualyElim: true,
    subSafetyCar: true,
    subRedFlag: true,
    subRain: true,
    subTrackLimits: true,
    subPenalties: true,
    subFlags: true,
    subRaceEvents: true,
  },
  [RADIO_TRIGGER_PRESETS.MINIMAL]: {
    tyreAlertsEnabled: true,
    damageAlertsEnabled: true,
    ersAlertsEnabled: false,
    brakesAlertsEnabled: false,
    fuelAlertsEnabled: false,
    rivalAlertsEnabled: false,
    pitAlertsEnabled: false,
    coachingAlertsEnabled: false,
    teammateAlertsEnabled: false,
    qualyAlertsEnabled: false,
    flagsPensAlertsEnabled: true,
    chatterCooldownSeconds: RADIO_ALERT_CONSTANTS.CHATTER_PRESETS.MINIMAL,
    subTyreWear: false,
    subTyrePuncture: true,
    subTyreThermal: false,
    subTyreCold: false,
    subTyreCondition: false,
    subTyreCrossover: true,
    subDamageWing: true,
    subDamageFloor: false,
    subDamageEngine: false,
    subDamageFaults: true,
    subEngineTemp: false,
    subErsLow: false,
    subErsClipping: false,
    subAeroZones: false,
    subBrakeTemp: false,
    subBrakeCold: false,
    subBrakeBias: false,
    subFuelDelta: false,
    subFuelMix: false,
    subUndercut: false,
    subRivalDefend: false,
    subRivalAttack: false,
    subPitWindow: false,
    subPitWindowClose: false,
    subPitCleanAir: false,
    subTyreSet: false,
    subPitLane: false,
    subPitEntryReminder: false,
    subSectorDelta: false,
    subStartProcedure: false,
    subInlapCooldown: false,
    subTeammateAhead: false,
    subTeammatePit: false,
    subQualyTraffic: false,
    subQualyInvalid: false,
    subQualyTime: false,
    subQualyElim: false,
    subSafetyCar: true,
    subRedFlag: true,
    subRain: false,
    subTrackLimits: false,
    subPenalties: true,
    subFlags: true,
    subRaceEvents: false,
  },
};

export function isRadioTriggerPreset(value: unknown): value is RadioTriggerPreset {
  return (Object.values(RADIO_TRIGGER_PRESETS) as unknown[]).includes(value);
}

/**
 * Returns the named preset whose switches and chatter cooldown match `state`, or `custom`.
 * Used for settings saved before the preset name was stored.
 */
export function detectTriggerPreset(state: TriggerPresetValues): RadioTriggerPreset {
  for (const [preset, values] of Object.entries(TRIGGER_PRESET_VALUES) as [
    NamedTriggerPreset,
    TriggerPresetValues,
  ][]) {
    const matches =
      values.chatterCooldownSeconds === state.chatterCooldownSeconds &&
      ALERT_TOGGLE_KEYS.every((key) => values[key] === state[key]);
    if (matches) return preset;
  }
  return RADIO_TRIGGER_PRESETS.CUSTOM;
}
