// Package tsgen writes TypeScript interfaces for the Go types the server sends as JSON, so the
// frontend's wire types come from the Go structs instead of being copied by hand.
//
// It follows the encoding/json rules through reflection:
//   - The property name is the json tag name, or the Go field name when there is no tag.
//   - Fields tagged "-" and unexported fields are skipped.
//   - omitempty and omitzero make a property optional.
//   - An embedded struct without a json name becomes `extends`.
//   - A `tstype:"..."` struct tag replaces the generated TypeScript type of a field verbatim.
//
// A type with its own MarshalJSON can send any shape, so the generator refuses it unless it is
// registered with Marshaler, together with the type whose fields describe its JSON.
package tsgen

import (
	"encoding"
	"encoding/json"
	"fmt"
	"go/token"
	"maps"
	"path"
	"reflect"
	"regexp"
	"slices"
	"strings"
	"time"
)

// Header starts every generated file.
const Header = "// Code generated by go run ./cmd/tsgen. DO NOT EDIT.\n"

var (
	jsonMarshalerType = reflect.TypeFor[json.Marshaler]()
	textMarshalerType = reflect.TypeFor[encoding.TextMarshaler]()
	timeType          = reflect.TypeFor[time.Time]()
	rawMessageType    = reflect.TypeFor[json.RawMessage]()
	identPattern      = regexp.MustCompile(`[A-Za-z_$][A-Za-z0-9_$]*`)
)

// Field is one JSON property of a struct, as encoding/json writes it.
type Field struct {
	Name     string
	Optional bool
}

type declaration struct {
	name    string
	goName  string
	extends []string
	lines   []string
	union   []string
	alias   string
	// idents are the identifiers used in tstype tags, so the file can import the generated
	// types they name.
	idents []string
}

// Generator collects the root types and writes one TypeScript file per Go package.
type Generator struct {
	roots      []reflect.Type
	unions     []unionSpec
	aliases    []aliasSpec
	marshalers map[reflect.Type]reflect.Type
	samples    map[reflect.Type]any
}

type aliasSpec struct {
	file, name, definition string
}

type unionSpec struct {
	file    string
	name    string
	members []reflect.Type
}

// New returns an empty Generator.
func New() *Generator {
	return &Generator{marshalers: map[reflect.Type]reflect.Type{}, samples: map[reflect.Type]any{}}
}

// Add registers root types. Everything they reference is generated too.
func (g *Generator) Add(values ...any) *Generator {
	for _, v := range values {
		g.roots = append(g.roots, reflect.TypeOf(v))
	}
	return g
}

// Marshaler registers a type with its own MarshalJSON. wire is the type whose fields describe
// the JSON it writes: the type itself when the method keeps the shape (for example it only
// sanitizes values, or its changed fields carry a tstype tag), or another struct when the
// method writes a different one. References to the type are written as the wire type.
//
// value is also kept as a sample (see MarshalerSample): fill in the fields that make the method
// write optional properties, so a test can check its output against the wire type.
func (g *Generator) Marshaler(value, wire any) *Generator {
	t := reflect.TypeOf(value)
	g.marshalers[t] = reflect.TypeOf(wire)
	g.samples[t] = value
	return g
}

// MarshalerSample returns the value registered with Marshaler for t.
func (g *Generator) MarshalerSample(t reflect.Type) any {
	return g.samples[t]
}

// Union registers `export type name = A | B | ...` in the file of the given Go package name.
func (g *Generator) Union(file, name string, members ...any) *Generator {
	spec := unionSpec{file: file, name: name}
	for _, m := range members {
		spec.members = append(spec.members, reflect.TypeOf(m))
	}
	g.unions = append(g.unions, spec)
	return g
}

// TypeAlias registers `export type name = definition;` in the file of the given Go package
// name, for shapes Go has no struct for (for example rows of a []map[string]any that a tstype
// tag refers to).
func (g *Generator) TypeAlias(file, name, definition string) *Generator {
	g.aliases = append(g.aliases, aliasSpec{file: file, name: name, definition: definition})
	return g
}

// Marshalers returns the registered MarshalJSON types and their wire types.
func (g *Generator) Marshalers() map[reflect.Type]reflect.Type {
	return g.marshalers
}

// JSONFields returns the properties the generator writes for a struct type, including the ones
// it inherits from embedded structs.
func JSONFields(t reflect.Type) ([]Field, error) {
	if t.Kind() != reflect.Struct {
		return nil, fmt.Errorf("%s is not a struct", t)
	}
	var fields []Field
	for sf := range fieldsOf(t) {
		switch {
		case sf.embedded:
			inner, err := JSONFields(sf.field.Type)
			if err != nil {
				return nil, err
			}
			fields = append(fields, inner...)
		default:
			fields = append(fields, Field{Name: sf.name, Optional: sf.optional})
		}
	}
	return fields, nil
}

type structField struct {
	field    reflect.StructField
	name     string
	optional bool
	embedded bool
	tsType   string
}

// fieldsOf yields the fields encoding/json writes for t, in declaration order.
func fieldsOf(t reflect.Type) func(yield func(structField) bool) {
	return func(yield func(structField) bool) {
		for i := range t.NumField() {
			f := t.Field(i)
			tag := f.Tag.Get("json")
			if tag == "-" {
				continue
			}
			name, opts, _ := strings.Cut(tag, ",")
			if f.Anonymous && name == "" && f.Type.Kind() == reflect.Struct {
				if !yield(structField{field: f, embedded: true}) {
					return
				}
				continue
			}
			if !f.IsExported() {
				continue
			}
			if name == "" {
				name = f.Name
			}
			optional := false
			for opt := range strings.SplitSeq(opts, ",") {
				if opt == "omitempty" || opt == "omitzero" {
					optional = true
				}
			}
			if !yield(structField{field: f, name: name, optional: optional, tsType: f.Tag.Get("tstype")}) {
				return
			}
		}
	}
}

// Generate returns the generated files, keyed by file name (Go package name + ".ts").
func (g *Generator) Generate() (map[string][]byte, error) {
	w := &writer{g: g, decls: map[reflect.Type]*declaration{}, names: map[string]reflect.Type{}, nameFile: map[string]string{}}
	for _, a := range g.aliases {
		if err := w.claim(a.name, nil); err != nil {
			return nil, err
		}
		w.nameFile[a.name] = a.file
	}
	for _, u := range g.unions {
		if err := w.claim(u.name, nil); err != nil {
			return nil, err
		}
		w.nameFile[u.name] = u.file
	}
	for _, t := range g.roots {
		if _, err := w.ref(t, "the registered roots"); err != nil {
			return nil, err
		}
	}
	for i := 0; i < len(w.queue); i++ {
		if err := w.declare(w.queue[i]); err != nil {
			return nil, err
		}
	}
	files := map[string]*file{}
	fileOf := func(name string) *file {
		if files[name] == nil {
			files[name] = &file{imports: map[string]map[string]bool{}}
		}
		return files[name]
	}
	for t, d := range w.decls {
		f := fileOf(fileName(t))
		f.decls = append(f.decls, d)
		for dep := range w.deps[t] {
			if other := fileName(dep); other != fileName(t) {
				f.addImport(other, w.decls[dep].name)
			}
		}
		for _, ident := range d.idents {
			if other, ok := w.nameFile[ident]; ok && other != fileName(t) {
				f.addImport(other, ident)
			}
		}
	}
	for _, a := range g.aliases {
		fileOf(a.file).decls = append(fileOf(a.file).decls, &declaration{name: a.name, alias: a.definition})
	}
	for _, u := range g.unions {
		d := &declaration{name: u.name}
		f := fileOf(u.file)
		for _, m := range u.members {
			m = w.wireType(m)
			md, ok := w.decls[m]
			if !ok {
				return nil, fmt.Errorf("union %s: member %s is not generated; add it as a root", u.name, m)
			}
			d.union = append(d.union, md.name)
			if other := fileName(m); other != u.file {
				f.addImport(other, md.name)
			}
		}
		f.decls = append(f.decls, d)
	}
	out := make(map[string][]byte, len(files))
	for name, f := range files {
		out[name+".ts"] = f.render()
	}
	return out, nil
}

type writer struct {
	g        *Generator
	decls    map[reflect.Type]*declaration
	names    map[string]reflect.Type
	nameFile map[string]string
	queue    []reflect.Type
	deps     map[reflect.Type]map[reflect.Type]bool
}

func fileName(t reflect.Type) string {
	return path.Base(t.PkgPath())
}

func (w *writer) wireType(t reflect.Type) reflect.Type {
	if wire, ok := w.g.marshalers[t]; ok {
		return wire
	}
	return t
}

// claim reserves a TypeScript name, so two Go types never share one.
func (w *writer) claim(name string, t reflect.Type) error {
	if prev, ok := w.names[name]; ok && (prev != t || t == nil) {
		return fmt.Errorf("TypeScript name %s is declared twice (%v and %v)", name, prev, t)
	}
	w.names[name] = t
	return nil
}

// ref returns the TypeScript type for t and queues the named structs it needs.
func (w *writer) ref(t reflect.Type, from string) (string, error) {
	switch t {
	case timeType:
		return "string", nil
	case rawMessageType:
		return "unknown", nil
	}
	if _, ok := w.g.marshalers[t]; ok {
		return w.named(w.wireType(t))
	}
	if implementsMarshaler(t) {
		return "", fmt.Errorf("%s (in %s) has its own MarshalJSON or MarshalText; register it with Marshaler", t, from)
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Pointer:
		inner, err := w.ref(t.Elem(), from)
		if err != nil {
			return "", err
		}
		return inner + " | null", nil
	case reflect.Slice, reflect.Array:
		if t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Uint8 {
			return "string", nil
		}
		inner, err := w.ref(t.Elem(), from)
		if err != nil {
			return "", err
		}
		if strings.Contains(inner, "|") {
			inner = "(" + inner + ")"
		}
		return inner + "[]", nil
	case reflect.Map:
		switch t.Key().Kind() {
		case reflect.String, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		default:
			return "", fmt.Errorf("%s (in %s): map key %s is not written as a JSON string", t, from, t.Key())
		}
		inner, err := w.ref(t.Elem(), from)
		if err != nil {
			return "", err
		}
		return "Record<string, " + inner + ">", nil
	case reflect.Struct:
		return w.named(t)
	default:
		return "", fmt.Errorf("%s (in %s): kind %s has no JSON form", t, from, t.Kind())
	}
}

func implementsMarshaler(t reflect.Type) bool {
	pt := reflect.PointerTo(t)
	return t.Implements(jsonMarshalerType) || pt.Implements(jsonMarshalerType) ||
		t.Implements(textMarshalerType) || pt.Implements(textMarshalerType)
}

func (w *writer) named(t reflect.Type) (string, error) {
	if t.Kind() != reflect.Struct {
		return w.ref(t, t.String())
	}
	if t.Name() == "" || strings.Contains(t.Name(), "[") {
		return "", fmt.Errorf("%s: only named, non-generic structs can be generated", t)
	}
	if _, ok := w.decls[t]; !ok {
		if err := w.claim(t.Name(), t); err != nil {
			return "", err
		}
		w.decls[t] = &declaration{name: t.Name(), goName: path.Base(t.PkgPath()) + "." + t.Name()}
		w.nameFile[t.Name()] = fileName(t)
		w.queue = append(w.queue, t)
	}
	return t.Name(), nil
}

// declare fills in the interface body of a queued struct.
func (w *writer) declare(t reflect.Type) error {
	d := w.decls[t]
	if w.deps == nil {
		w.deps = map[reflect.Type]map[reflect.Type]bool{}
	}
	deps := map[reflect.Type]bool{}
	w.deps[t] = deps
	for sf := range fieldsOf(t) {
		if sf.embedded {
			base := sf.field.Type
			if !token.IsExported(base.Name()) {
				return fmt.Errorf("%s: embedded %s must be a named exported struct", t, base)
			}
			name, err := w.named(w.wireType(base))
			if err != nil {
				return err
			}
			d.extends = append(d.extends, name)
			deps[w.wireType(base)] = true
			continue
		}
		tsType := sf.tsType
		if tsType != "" {
			d.idents = append(d.idents, identPattern.FindAllString(tsType, -1)...)
		} else {
			ft := sf.field.Type
			if sf.optional && ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			var err error
			if tsType, err = w.ref(ft, t.String()+"."+sf.field.Name); err != nil {
				return err
			}
			for _, named := range namedStructs(ft, w.wireType) {
				deps[named] = true
			}
		}
		opt := ""
		if sf.optional {
			opt = "?"
		}
		d.lines = append(d.lines, fmt.Sprintf("  %s%s: %s;", propertyName(sf.name), opt, tsType))
	}
	return nil
}

// namedStructs lists the named structs a field type refers to, so the file can import them.
func namedStructs(t reflect.Type, wire func(reflect.Type) reflect.Type) []reflect.Type {
	if t == timeType || t == rawMessageType {
		return nil
	}
	if w := wire(t); w != t {
		return []reflect.Type{w}
	}
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
		return namedStructs(t.Elem(), wire)
	case reflect.Struct:
		return []reflect.Type{t}
	}
	return nil
}

func propertyName(name string) string {
	for i, r := range name {
		ok := r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

type file struct {
	decls   []*declaration
	imports map[string]map[string]bool
}

func (f *file) addImport(from, name string) {
	if f.imports[from] == nil {
		f.imports[from] = map[string]bool{}
	}
	f.imports[from][name] = true
}

func (f *file) render() []byte {
	var b strings.Builder
	b.WriteString(Header)
	for _, from := range slices.Sorted(maps.Keys(f.imports)) {
		names := slices.Sorted(maps.Keys(f.imports[from]))
		fmt.Fprintf(&b, "import type { %s } from './%s';\n", strings.Join(names, ", "), from)
	}
	slices.SortFunc(f.decls, func(a, c *declaration) int { return strings.Compare(a.name, c.name) })
	for _, d := range f.decls {
		b.WriteString("\n")
		if d.union != nil {
			fmt.Fprintf(&b, "export type %s = %s;\n", d.name, strings.Join(d.union, " | "))
			continue
		}
		if d.alias != "" {
			fmt.Fprintf(&b, "export type %s = %s;\n", d.name, d.alias)
			continue
		}
		fmt.Fprintf(&b, "/** Go: %s */\n", d.goName)
		extends := ""
		if len(d.extends) > 0 {
			extends = " extends " + strings.Join(d.extends, ", ")
		}
		if len(d.lines) == 0 {
			fmt.Fprintf(&b, "export interface %s%s {}\n", d.name, extends)
			continue
		}
		fmt.Fprintf(&b, "export interface %s%s {\n%s\n}\n", d.name, extends, strings.Join(d.lines, "\n"))
	}
	return []byte(b.String())
}
